### PR TITLE
correctly use norm if provided

### LINKED ISSUE #5: Colorbar is ignoring the norm
It seems that the colorbar is not providing `norm` to the `PatchCollection`, resulting in the wrong colors being plotted.

### PR DESCRIPTION
**Pull request by cphyc**
Should fix #5 .

### CODE REVIEW

**Comment by cphyc** [comment]
Seems like the expected image is not up-to-date anymore. I attached the version I got
example1

**Comment by ppinard** [comment]
Thank you very much for finding and fixing this bug. I suspect that the test failed initially because of the release of matplotlib 2.0. I am away on business, I will have a final look and merge your pull request in a few days.

**Comment by cphyc** [comment]
Thanks.
I also uploaded a version for python 3.6 so that you can roll-out a release for this version.

**Comment by ppinard** [comment]
I cleaned up a bit your commit to remove some autoformatting. I think it is better since the diff now highlights the modifications.

**Comment by ppinard** [comment]
Fix in release [0.3.4](https://github.com/ppinard/matplotlib-colorbar/releases/tag/0.3.4). Thank you for your contribution.

**Pull request merged**
